apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-sample-app
  template:
    metadata:
      labels:
        name: k8s-sample-app
    spec:
      containers:
      - name: k8s-sample-app
        image: {{.Values.image}}
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: NAME
            value: Default
          - name: SDKKEY
            value: {{.Values.sdkKey}}

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-sample-app
  labels:
    app: k8s-sample-app
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-sample-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  defaultBackend:
    service:
      name: k8s-sample-app
      port:
        number: 8080
