{{- if .Values.createNamespace}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}
{{- end}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: k8s-sample-app
  template:
    metadata:
      labels:
        run: k8s-sample-app
    spec:
      containers:
      - name: k8s-sample-app
        image: {{.Values.image}}
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: NAME
            value: Default
          - name: SDKKEY
            value: {{.Values.sdkKey}}
