apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: k8s-sample-app
  template:
    metadata:
      labels:
        run: k8s-sample-app
    spec:
      containers:
      - name: k8s-sample-app
        image: {{.Values.image}}
        ports:
          - containerPort: 3000
            protocol: TCP
        env:
          - name: NAME
            value: Default
          - name: SDKKEY
            value: {{.Values.sdkKey}}

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-sample-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: k8s-sample-app
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  defaultBackend:
    service:
      name: k8s-sample-app
      port:
        number: 3000
