apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-sample-app
  template:
    metadata:
      labels:
        name: k8s-sample-app
    spec:
      containers:
      - name: k8s-sample-app
        image: {{.Values.image}}
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: NAME
            value: Patrick

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-sample-app
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: k8s-sample-app
  sessionAffinity: None
  type: NodePort
