---
apiVersion: v1
kind: Service
metadata:
  name: k8s-sample-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: k8s-sample-app
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  defaultBackend:
    service:
      name: k8s-sample-app
      port:
        number: 8080
